# Generated by Django 3.1.5 on 2021-01-31 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudajax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruduser',
            old_name='username',
            new_name='name',
        ),
    ]
